version: '3.9'

services:
  kali:
    build: 
      context: .
      dockerfile: docker/kali.dockerfile
    # networks:
    #   - local
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    pid: "host"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: '8G'

    depends_on:
      - mongo
      - postgres
      - redis

  mongo:
    image: mongo:latest
    volumes:
      - postgres-data:/data/db
    ports:
      - 27017:27017
    networks:
      - local

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - local

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local
    depends_on:
      - postgres

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - local

volumes:
  mongo-data:
  postgres-data:
  pgadmin-data:

networks:
  local:
    driver: bridge